name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    uses: mupinnn/parachute/.github/workflows/deploy.yml@main
    with:
      deployment-name: chat-db
      type: compose
      compose-files: "docker-compose.yml docker-compose.prod.yml"
    secrets:
      parachute-url: ${{ secrets.PARACHUTE_URL }}
      deploy-token: ${{ secrets.PARACHUTE_DEPLOY_TOKEN }}
      tailscale-oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
      tailscale-oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
